apps:

  - script: server/graphql.js
    name: pd:graphql
    autostart: false
    exec_mode: cluster_mode
    node_args: -r babel-register -r babel-polyfill
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
      DEBUG: "*"
    env_gqlog:
      GQLOG: gqlog

  - script: server/index.js
    name: pd:web
    autostart: false
    exec_mode: cluster_mode
    node_args: -r babel-register -r babel-polyfill
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
