
export const EntityTypes = [
  'Action',
  'ApplicationRole',
  'ApprovalCycleConfig',
  'AssociationConfig',
  'CategoryHierarchy',
  'CharacteristicConfig',
  'ChoiceList',
  'DictionaryEntry',
  'Document',
  'DocumentClass',
  'DocumentType',
  'Layout',
  'LifeCycleConfig',
  'LineItemConfig',
  'NavigationHierarchy',
  'NavigationNode',
  'OrganizationHierarchy',
  'Organization',
  'SectionConfig',
  'User',
];

// EntityType ===>> Revision Route
export const entityTypeToRevisionRoute = {
  Action: 'actions/revisions',
  ApplicationRole: 'applicationroles/revisions',
  ApprovalCycleConfig: 'approvalcycleconfigs/revisions',
  AssociationConfig: 'associationconfigs/revisions',
  CategoryHierarchy: 'categoryhierarchies/revisions',
  CharacteristicConfig: 'characteristicconfigs/revisions',
  ChoiceList: 'choicelists/revisions',
  DictionaryEntry: 'dictionaryentries/revisions',
  Document: 'documents/revisions',
  DocumentClass: 'documentclasses/revisions',
  DocumentType: 'documenttypes/revisions',
  Layout: 'templatelayouts/revisions',
  LifeCycleAction: 'lifecycles/actions',
  LifeCycleConfig: 'lifecycleconfigs',
  LineItemConfig: 'lineitemconfigs/revisions',
  NavigationHierarchy: 'navigationhierarchies/revisions',
  NavigationNode: 'navigationnodes/revisions',
  OrganizationHierarchy: 'organizationhierarchies/revisions',
  Organization: 'organizations/revisions',
  SectionConfig: 'sectionconfigs/revisions',
  User: 'users',
};

// EntityType ===>> Family Route
export const entityTypeToFamilyRoute = {
  Action: 'actions',
  ApplicationRole: 'applicationroles',
  ApprovalCycleConfig: 'approvalcycleconfigs',
  AssociationConfig: 'associationconfigs',
  CategoryHierarchy: 'categoryhierarchies',
  CharacteristicConfig: 'characteristicconfigs',
  ChoiceList: 'choicelists',
  DictionaryEntry: 'dictionaryentries',
  Document: 'documents',
  DocumentClass: 'documentclasses',
  DocumentType: 'documenttypes',
  Layout: 'templatelayouts',
  LifeCycleAction: 'lifecycles/actions',
  LifeCycleConfig: 'lifecycleconfigs',
  LineItemConfig: 'lineitemconfigs',
  NavigationHierarchy: 'navigationhierarchies',
  NavigationNode: 'navigationnodes',
  OrganizationHierarchy: 'organizationhierarchies',
  Organization: 'organizations',
  SectionConfig: 'sectionconfigs',
  User: 'users',
};

////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

export const entityTypeToPluralLabel = {
  Action: 'Actions',
  ApplicationRole: 'Application Roles',
  ApprovalCycleConfig: 'Approval Cycle Configurations',
  AssociationConfig: 'Association Configurations',
  CharacteristicConfig: 'Characteristic Configurations',
  CategoryHierarchy: 'Category Hierarchies',
  ChoiceList: 'Choice Lists',
  Culture: 'Cultures',
  DictionaryEntry: 'Dictionary Entries',
  Document: 'Documents',
  DocumentClass: 'Document Classes',
  DocumentType: 'Document Types',
  Layout: 'Template Layouts',
  LifeCycleConfig: 'Life Cycle Configurations',
  LineItemConfig: 'Line Item Configurations',
  NavigationHierarchy: 'NavigationHierarchies',
  NavigationNode: 'NavigationNodes',
  OrganizationHierarchy: 'Organization Hierarchies',
  Organization: 'Organizations',
  SectionConfig: 'Section Configurations',
  SectionLineItemConfig: 'Section Line Item Configurations',
  User: 'User Profiles',
};

export const entityListLabels = {
  Action: 'Action',
  ApplicationRole: 'Application Role',
  ApprovalCycleConfig: 'Approval Cycle Configuration',
  Assignment: 'Assignment',
  AssociationConfig: 'Association Configuration',
  CategoryHierarchy: 'Category Hierarchy',
  CharacteristicConfig: 'Characteristic Configuration',
  ChoiceList: 'Choice List',
  DictionaryEntry: 'Dictionary Entry',
  Culture: 'Culture',
  Document: 'Document',
  DocumentClass: 'Document Class',
  DocumentType: 'Document Type',
  LifeCycleConfig: 'Life Cycle Configuration',
  LineItemConfig: 'Line Item Configuration',
  NavigationNode: 'Navigation Node',
  NavigationHierarchy: 'Navigation Hierarchy',
  Organization: 'Organization',
  OrganizationHierarchy: 'Organization Hierarchy',
  SectionConfig: 'Section Configuration',
  TemplateLayout: 'Template Layout',
  User: 'User Profile',
};

// EntityType ===>> Simple Route
export const entityTypeToSimpleRoute = {
  Action: 'actions/simple',
  ApplicationRole: 'applicationroles/simple',
  ApprovalCycleConfig: 'approvalcycleconfigs/simple',
  AssociationConfig: 'associationconfigs/simple',
  CategoryHierarchy: 'categoryhierarchies/simple',
  CharacteristicConfig: 'characteristicconfigs/simple',
  ChoiceList: 'choicelists/simple',
  DictionaryEntry: 'dictionaryentries/simple',
  Document: 'documents/simple',
  DocumentClass: 'documentclasses/simple',
  DocumentType: 'documenttypes/simple',
  Layout: 'templatelayouts/simple',
  LifeCycleAction: 'lifecycles/actions/simple',
  LifeCycleConfig: 'lifecycles/simple',
  LineItemConfig: 'lineitemconfigs/simple',
  NavigationHierarchy: 'navigationhierarchies/simple',
  NavigationNode: 'navigationnodes/simple',
  OrganizationHierarchy: 'organizationhierarchies/simple',
  Organization: 'organizations/simple',
  SectionConfig: 'sectionconfigs/simple',
  User: 'users/simple',
};

// EntityLabel ===>> Family Route
export const entityLabelToFamilyRoute = {
  Action: 'actions',
  'Application Role': 'applicationroles',
  'Approval Cycle Config': 'approvalcycleconfigs',
  'Association Config': 'associationconfigs',
  'Category Hierarchy': 'categoryhierarchies',
  'Characteristic Config': 'characteristicconfigs',
  'Choice List': 'choicelists',
  'Dictionary Entry': 'dictionaryentries',
  Document: 'documents',
  'Document Class': 'documentclasses',
  Layout: 'templatelayouts',
  'Lifecycle Config': 'lifecycleconfigs',
  'Line Item Config': 'lineitemconfigs',
  'Navigation Hierarchy': 'navigationhierarchies',
  'Navigation Node': 'navigationnodes',
  Organization: 'organizations',
  'Section Config': 'sectionconfigs',
  User: 'users',
};

// Route ===>> Entity Type
export const routeToEntityType = {
  actions: 'Action',
  applicationroles: 'ApplicationRole',
  approvalcycleconfigs: 'ApprovalCycleConfig',
  associationconfigs: 'AssociationConfig',
  categoryhierarchies: 'CategoryHierarchy',
  characteristicconfigs: 'CharacteristicConfig',
  choicelists: 'ChoiceList',
  dictionaryentries: 'DictionaryEntry',
  documents: 'Document',
  documentclasses: 'DocumentClass',
  documenttypes: 'DocumentType',
  lifecycleconfigs: 'LifeCycleConfig',
  lineitemconfigs: 'LineItemConfig',
  navigationhierarchies: 'NavigationHierarchy',
  navigationnodes: 'NavigationNode',
  organizationhierarchies: 'OrganizationHierarchy',
  organizations: 'Organization',
  sectionconfigs: 'SectionConfig',
  templatelayouts: 'TemplateLayout',
  users: 'User',
};

// Entity Type ===>> Tree Node Type
export const entityTypeToTreeNode = {
  CategoryHierarchy: 'dictionaryentries',
  ChoiceList: 'dictionaryentries',
  NavigationHierarchy: 'navigationnodes',
  OrganizationHierarchy: 'organizations',
};


export const entityTypeToLabel = {
  Action: 'Action',
  ApprovalCycleConfig: 'Approval Cycle Configuration',
  ApplicationRole: 'Application Role',
  Assignment: 'Assignment',
  AssociationConfig: 'Association Configuration',
  CategoryHierarchy: 'Category Hierarchy',
  CharacteristicConfig: 'Characteristic Configuration',
  ChoiceList: 'Choice List',
  Culture: 'Culture',
  DictionaryEntry: 'Dictionary Entry',
  Document: 'Document',
  DocumentClass: 'Document Class',
  DocumentType: 'Document Type',
  LifeCycleConfig: 'Life Cycle Configuration',
  LineItemConfig: 'Line Item Configuration',
  NavigationHierarchy: 'Navigation Hierarchy',
  NavigationNode: 'Navigation Node',
  OrganizationHierarchy: 'Organization Hierarchy',
  Organization: 'Organization',
  SectionConfig: 'Section Configuration',
  SectionLineItemConfig: 'Section Line Item Configuration',
  TemplateLayout: 'Template Layout',
  User: 'User Profile',
};

export const supportedCreationEntities = [
  'Action',
  'Application Role',
  'Approval Cycle Config',
  'Association Config',
  'Category Hierarchy',
  'Characteristic Config',
  'Choice List',
  'Dictionary Entry',
  'Document',
  'Document Class',
  'Layout',
  'Line Item Config',
  'Navigation Node',
  'Navigation Hierarchy',
  'Organization',
  'Section Config',
  'Sequence',
  'User',
];

export const propertyTypes = [
  'Boolean',
  'Category',
  // 'ControlNumber',
  'Date',
  'Decimal',
  'Entity',
  'EntityList',
  'Float',
  'Integer',
  'RoleList',
  'RichText',
  'Text',
];

export const revisionableList = [
  'actions',
  'applicationroles',
  'approvalcycleconfigs',
  'associationconfigs',
  'categoryhierarchies',
  'characteristicconfigs',
  'choicelists',
  'dictionaryentries',
  'documents',
  'documentclasses',
  'documenttypes',
  'lineitemconfigs',
  'navigationhierarchies',
  'navigationnodes',
  'organizations',
  'organizationhierarchies',
  'sectionconfigs',
  'templatelayouts',
];
